[project]
name = "chat-bot"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "pandas (>=2.2.3,<3.0.0)",
    "fastapi (==0.115.9)",
    "gradio (>=5.29.0,<6.0.0)",
    "langchain (>=0.3.25,<0.4.0)",
    "langchain-community (>=0.3.24,<0.4.0)",
    "chromadb (>=1.0.9,<2.0.0)",
    "sentence-transformers (>=4.1.0,<5.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "pypdf (>=5.5.0,<6.0.0)",
    "langgraph (>=0.4.3,<0.5.0)",
    "funcsigs (>=1.0.2,<2.0.0)"
]

[tool.poetry]
packages = [{include = "chat_bot", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
